# CFLAGS sets the environmental variables
#  Wall to show all error flagsdd and -g to put in debugging mode
CFLAGS=-Wall -g

all: ex17_variable_size ex17_fixed_size

verbose_all:
	cc -Wall -g ./ex17_variable_size.c -o ex17_variable_size

clean:
	rm -f ex17

random:
	echo 'hello world;'
